export const blogs = [
  {
    id: 1,
    baslik: "Rüzgâr Deneyi",
    picture: "/img/kinder1.jpg",
    kazanim: "Nesne/durum/olayla ilgili tahminlerini değerlendirir. ",
    malzeme: [
      "Kaşık",
      "tüy",
      "kâğıt",
      "pamuk",
      "blok",
      "taş (birer adet)",
      "aile üyelerinin sayısı kadar pipet",
    ],
    uygulama: [
      "Aile üyeleri çember olarak yere otururlar.",
      "Ebeveyn ‘Beraber rüzgâr deneyi yapacağız.’ Der. Rüzgârı, aile üyelerine hem sesle hem de nefes üfleyerek gösterir. Sonra ‘Şimdi siz de benimle beraber rüzgâr oluşturun. ‘der.",
      "Malzemeleri yan yana koyar ve aile üyelerine neler gördüklerini sorar. “Önümüzde hangi nesneler var? Kaşık, tüy, pamuk, kâğıt, blok, taş var burada. Peki, sizce bu nesnelerden hangileri rüzgârda hareket eder, hangileri edemez?” diye sorar ve aile üyelerinin fikirlerini alır.",
      "Aile üyelerine pipetleri dağıtır. Ellerindeki pipetler yardımıyla hava üflemeleri ve nesneleri hareket ettirmelerini ister. “Şimdi sırayla bu malzemelerin yanına geleceksiniz ve pipetinizle üfleyerek buradaki nesneleri hareket ettirmeye çalışacaksınız.” Der.",
      "Daha sonra bazı nesnelerin hareket edebildiğine ancak, bazı nesnelerin ise hareket edemediğine dikkat çeker. Neden bazılarının hareket ettiği, bazılarının hareket edemediği sorar ve açıklama yapar. “Bazı nesneler ağır olduğu için havanın da gücü buna yetmediği için hareket ettiremedik. Kaşık, blok, taş gibi. Ancak bazıları hafif olduğu için havanın gücü de buna yeterliydi ve hareket ettirebildik. Tüy, pamuk, kâğıt gibi.”",
      "Yaşadıkları deneyim sonrasında rüzgârın ne olduğu sorar ve rüzgârı tarif etmelerini ister. “Rüzgâr nedir sizce? “diye sorar ve cevapları dinler. “Hava hareket ettiğinde rüzgâr oluyor. Çok kuvvetli olduğunda da buradaki gibi nesneleri hareket ettiriyor.” diyerek tekrar eder.",
    ],
    yazar: "Ayşe Öğretmen",
    yayin_tarihi: "2024-05-13",
    kategori: "Eğitim",
  },
  {
    id: 2,
    baslik: "Benim de Sorumluluklarım Var",
    picture: "/img/kinder2.jpg",
    kazanim: "Bir işi/görevi başarmak için kararlılık gösterir.",
    malzeme: ["Leğen", "deterjanlı su", "bez gibi temizlik malzemeleri"],
    uygulama: [
      "Aile üyeleri ile evde bahar temizliği yaparlar.",
      "Leğenin içine sabunlu su koyulur. Ebeveyn çocuğa kendi odasındaki eşyaların nasıl tozunu sileceği, oyuncaklarını nasıl sileceği ve düzenleyeceğini gösterir ve beraber yaparlar.",
      "Evde kırık veya yırtık şeyler var ise incelenip, tamir edilecekler varsa tamir ederler.",
      "Evi güzelleştirmek için başka neler yapılabileceği hakkında konuşurlar. Fikirler değerlendirilip, uygularlar. Evi temiz ve düzenli tutmak için neler yapılabilir, herkesin sorumlulukları ile ilgili paylaşımlarda bulunurlar.",
      "Temizlik ve güzelleştirme çalışmaları sonrasında birlikte bir aile fotoğrafı çekerler ve anı köşesi oluşturulabilirler.",
      "Güvenlik Notu: Kullanılan deterjanın çocuklara zarar vermeyecek özellikte olmasına dikkat edilmelidir. Yere su dökülmesi durumda çocukların kaymamaları için gerekli önlemler alınmalıdır.",
    ],
    yazar: "Mehmet Öğretmen",
    yayin_tarihi: "2024-05-12",
    kategori: "Eğitim",
  },
  {
    id: 3,
    baslik: "Bil Bakalım Ne Yapıyorum? ",
    picture: "/img/kinder3.jpg",
    kazanim: "Konuşurken dil bilgisi yapılarını kullanır.",
    malzeme: [
      "Hareket listesi: (Koşmak, Dişlerini fırçalamak, Yazı yazmak, Dondurma yalamak, Su içmek, Oturmak, Yıkanmak, Tırmanmak, Yemek yemek, Gülmek, Uçmak, Düşmek, Uyumak, Ağlamak, Kitap okumak, Telefonda konuşmak vb.)",
    ],
    uygulama: [
      "Aile üyeleri ‘U’ düzeninde oturur.",
      "Ebeveyn, aile üyelerine “Bugün sizlerle ‘Bil bakalım’ oyununu oynayacağız. Ben sağımdaki kişinin kulağına bir hareketi canlandırmasını söyleyeceğim. O hareketi canlandıracak ve siz de onun ne yaptığını bulacaksınız.” Der.",
      "Sağ taraftan başlayarak seçilen kişiye listeden, diğer kişilerin duymayacağı şekilde, kulağına bir hareketi söyler ve bu hareketi canlandırmasını ister.·Örneğin, çocuğa koşması söylenir. Diğer aile üyelerine, onun ne yaptığı aşağıdaki şekilde sorulur: o “…… (çocuğun adı) ne yapıyor?” diye sorar, cevapları dinler. o “…… (çocuğun adı) koşuyor.” diyerek doğru cevabı tekrar ederler.",
      "Aile üyelerinin cevapları doğru da olsa, yanlış da olsa, ebeveyn doğru cevabı bütün aile üyeleriyle tekrar eder. Ardından, herkes hareketi birlikte yapar.",
      "Daha sonra başka bir aile üyesi seçilerek oyuna devam ederler. Ona da listeden farklı bir hareket söyler ve aynı şekilde uygulama yaparlar. Listedeki tüm komutları yaptıktan sonra canlandırılan hareketler hakkında konuşmalar yaparlar.",
      "“…… sen ne yaptın?”, “……. ne yaptı?” ,“Bu oyunda kim yemek yedi?” diye aile üyelerine sorular sorar.",
      "Hareketleri aile üyelerinin tahmin etmesi sağlandıktan sonra etkinliği bitirirler.",
    ],
    yazar: "Fatma Öğretmen",
    yayin_tarihi: "2024-05-11",
    kategori: "Ebeveynlik",
  },
  {
    id: 4,
    baslik: "Marakas",
    picture: "/img/kinder4.jpg",
    kazanim: "Küçük kaslarını kullanarak koordineli hareketler yapar.",
    malzeme: [
      "Aile üyesi sayısı kadar 500 ml’lik pet şişe",
      "5 adet kâse",
      "pet şişelerin sığabileceği bir kutu",
      "bulgur",
      "nohut",
      "makarna",
      "mercimek gibi malzemeler",
      "Hazırlık: Malzemeleri kaselere karışık şekilde bölüştürün. ",
    ],
    uygulama: [
      "Aile üyeleriyle birlikte masaya otururlar",
      "Ebeveynlerden biri “Bugün hep birlikte ‘marakas’ isimli bir müzik aleti yapacağız.” der",
      "Her aile üyesine bir adet pet şişe verilir. İçinde farklı malzemelerin (bulgur, nohut, makarna vb.) bulunduğu kâseler masanın üstüne koyulur. Malzemelerin neler olduğu sorar ve büyüklükleri bakımından karşılaştırırlar. “Nohut mu, yoksa bulgur mu daha küçük?” gibi.",
      "Ebeveyn, aile üyelerinden malzemelerden biraz alıp, pet şişelerine doldurmalarını ister. Doldurma işlemi bittikten sonra, pet şişelerinin kapaklarını sıkıca kapatmalarını söyler.",
      "Ebeveyn “Marakaslarımız hazır. Marakasların nasıl ses çıkardığını merak ediyor musunuz? Sesini duymak için sallamanız yeterli.” der. Aile üyelerinin marakasları bir süre sallamalarına fırsat verir.",
      "Marakaslar ellerinde, herkes ile ayakta bir çember olurlar ve ebeveyn oyunu anlatır. Bir aile üyesinin ismi söylendikten sonra hep birlikte marakasların sallanacağını söyler. “Şimdi sıra ile her birimiz ismimizi söyleyeceğiz. Ama birisi ismini söyledikten sonra, hepimiz marakaslarımızı sallayacağız.” der.",
      "Örnek olmak için önce ebeveyn ismini söyler, ardından herkesin marakasları sallamasını ister. Sonra yanındaki aile üyesinden ismini söylemesini ister. İsmini söyledikten sonra, herkesin marakaslarını sallamalarını hatırlatır. Tüm aile üyeleri isimlerini söyleyene kadar uygulama devam eder. Ardından farklı isimler ve eşyalarla oyun devam eder.",
    ],
    yazar: "Ali Öğretmen",
    yayin_tarihi: "2024-05-10",
    kategori: "Eğitim",
  },
  // {
  //   id: 5,
  //   baslik: "Okul Öncesi Çocuklarda Davranış Sorunları",
  // picture:'/img/.jpg',
  // kazanim:"",
  //   malzeme:
  //     "Davranış sorunları, okul öncesi sınıflarda yaygındır. Bu blog yazısında, okul öncesi çocuklarda davranış sorunlarının nedenlerini ve nasıl ele alınacağını tartışacağız.",
  //     uygulama:[],
  //   yazar: "Elif Öğretmen",
  //   yayin_tarihi: "2024-05-09",
  //   kategori: "Eğitim",
  // },
  // {
  //   id: 6,
  //   baslik: "Okul Öncesi Eğitimin Önemi",
  // picture:'/img/.jpg',
  // kazanim:"",
  //   malzeme:
  //     "Okul öncesi eğitim, çocukların gelişiminde önemli bir rol oynar. Bu blog yazısında, okul öncesi eğitimin faydalarını ve neden önemli olduğunu tartışacağız.",
  //     uygulama:[],
  //   yazar: "Ahmet Öğretmen",
  //   yayin_tarihi: "2024-05-08",
  //   kategori: "Eğitim",
  // },
];
